// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GetNews struct {
	News []*News `json:"news,omitempty"`
}

type Mutation struct {
}

type NewNews struct {
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Img         *string `json:"img,omitempty"`
}

type Query struct {
}

type Subscription struct {
}
